## Site settings title: Kole
email: colleowino@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am a code junky, data enthusiast and design buff. 
  Trying to create a better world the only way I know how, coding!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://colleowino.github.io"
twitter_username: colleowino
github_username: colleowino 
facebook_username:  colleowino
header-img: img/home-new.jpg
title: "colleowino"
tagline: "ship it, now!"

# Dependencies
markdown: kramdown
highlighter: rouge

#permalinks
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-seo-tag]

#stop crashing
version: 2.1.0
github: 
repo: https://github.com/colleowino
url: colleowino.com
author:
  name: 'colle owino'
  url: https://twitter.com/colleowino
